Django_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('blog/',include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('',include('single_pages.urls')),
    path('practice/',include('practice.urls')),
    path('forcast/',include('forcast.urls')),
    path('baemin/',include('baemin.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

baemin/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('<int:pk>/new/', views.order_new),
    path('profile/', views.profile, name='profile'),
]

blog/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('search/<str:q>/',views.PostSearch.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/',views.PostCreate.as_view()),
    path('tag/<str:slug>/',views.tag_page),
    path('category/<str:slug>/', views.PostList.category_page),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
    # path('', views.index),
    path('<int:pk>/new_comment/', views.new_comment),
    path("update_comment/<int:pk>/", views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete-comment'),
    
    
    
]

baemin/models.py
from django.conf import settings
from django.db import models

class Shop(models.Model):
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=20)
    addr = models.CharField(max_length=100)

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/baemin/{self.pk}/new/'


class Item(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return self.name


class Order(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item_set = models.ManyToManyField(Item)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-id',)

    @property
    def total(self):
        return sum(item.price for item in self.item_set.all())

baemin/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    def __init__(self, shop, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_set'].queryset = self.fields['item_set'].queryset.filter(shop=shop)

    class Meta:
        model = Order
        fields = ('item_set',)

baemin/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from .models import Shop,Order
from .forms import OrderForm


def index(request):
    return render(request, 'baemin/index.html', {
        'shop_list': Shop.objects.all(),
    })

@login_required
def profile(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'baemin/profile.html', {'orders': orders})


@login_required
def order_new(request, pk):
    shop = get_object_or_404(Shop, id=pk)
    if request.method == 'POST':
        form = OrderForm(shop, request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.shop = shop
            order.save()
            form.save_m2m()
            return redirect('profile')
    else:
        form = OrderForm(shop)
    return render(request, 'baemin/order_form.html', {
        'form': form,
        'shop': shop,
    })

blog/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView
from .models import Post,Category,Tag,Comment
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.utils.text import slugify
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.db.models import Q

#CBV로 페이지 만들기
class PostList(ListView):
    model = Post #이게 이름 기본이 된다 주의 해야됨 _list.html
    # template_name = 'blog/index.html'
    ordering = '-pk'
    paginate_by = 5
    
    def get_context_data(self, **kwargs):
        context = super(PostList,self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        
        return context
    
    def category_page(request,slug):
        # category = Category.objects.get(slug=slug)
        
        if slug == 'no_category':
            category = '미분류'
            post_list = Post.objects.filter(category=None)
        
        else:
            category = Category.objects.get(slug=slug)
            post_list = Post.objects.filter(category=category)
        
        return render(
            request,
            'blog/post_list.html',
            {
                'post_list': post_list,
                'categories': Category.objects.all(),
                'no_category_post_count': Post.objects.filter(category=None).count(),
                'category' : category,
            }
        )



class PostDetail(DetailView):
    model = Post # _detail.html
    
    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
        return context
    
class PostCreate(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Post
    fields = ['title','hook_text','content','head_image','file_upload','category']

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff
    
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)
            
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()
                
                tags_str = tags_str.replace(',',';')
                tags_list = tags_str.split(';')
                
                for t in tags_list:
                    t=t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(name=t)
                    if is_tag_created:
                        tag.slug = slugify(t,allow_unicode=True)
                        tag.save()
                    self.object.tags.add(tag)
                    
            return response
            
        else:
            return redirect('/blog/')    
        
class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    fields = ['content']
    template_name = 'blog/comment_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super().dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
        
class PostSearch(PostList):
    paginate_by = None
    
    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains = q) | Q(tags__name__contains=q)
        ).distinct()
        return post_list
    
    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q= self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'
        
        return context

def delete_comment(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title','hook_text','content','head_image','file_upload','category','tags']
    
    template_name = 'blog/post_update_form.html'
    
    def get_context_data(self, **kwargs):
        context = super(PostUpdate,self).get_context_data()
        if self.object.tags.exists():
            tags_str_list = list()
            for t in self.object.tags.all():\
                tags_str_list.append(t.name)
            context['tags_str_default'] = '; '.join(tags_str_list)
            
        return context
    
    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tags.clear()
        
        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',',';')
            tags_list = tags_str.split(';')
            
            for t in tags_list:
                t=t.strip()
                tag,is_tag_created = Tag.objects.get_or_create(name=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tags.add(tag)
        return response
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate,self).dispatch(request,*args,**kwargs)
        else:
            raise PermissionDenied

    # def single_post_page(request,pk):
#     post =Post.objects.get(pk=pk)
    
#     return render(
#         request,
#         'blog/single_post_page.html',
#         {
#             'post':post,
#         }
#     )

def tag_page(request, slug):
    tag = Tag.objects.get(slug=slug)
    post_list = tag.post_set.all()
    
    return render(
        request,
        'blog/post_list.html',
        {
            'post_list': post_list,
            'tag': tag,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category = None).count()
        }
    )
    
def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == "POST":
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        return PermissionDenied

baemin/templates/baemin/index.html
{% extends "baemin/layout.html" %}

{% block content %}
    <h3>가게목록</h3>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>가게명</th>
                <th>전화번호</th>
                <th>주소</th>
                <th>주문하기</th>
            </tr>
        </thead>
        <tbody>
            {% for shop in shop_list %}
                <tr>
                    <td>{{ shop.name }}</td>
                    <td>{{ shop.tel }}</td>
                    <td>{{ shop.addr }}</td>
                    <td><a href="{{ shop.get_absolute_url }}" class="btn btn-primary">주문하기</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

baemin/templates/baemin/layout.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8" />
        <title>{{ user }} 접속중</title>

        <link href="{% static 'blog/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

        <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
                integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
                integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
                integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
                crossorigin="anonymous"></script>
    
        <script src="https://kit.fontawesome.com/89a12d4a7e.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    </head>
    <body>
        {% include 'blog/navbar.html'%}

        {% block content %}
        {% endblock %}

        <div class="fixed-bottom">
            {% include 'blog/footer.html' %}
        </div>
    </body>
</html>

baemin/templates/baemin/order_form.html
{% extends "baemin/layout.html" %}

{% block content %}
    <h3>{{ shop.name }} 주문</h3>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

baemin/templates/baemin/profile.html
{% extends "baemin/layout.html" %}

{% block content %}
<h3>{{ user }}'s Profile </h3>
<h4>주문내역</h4>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>가게명</th>
      <th>주문상품</th>
      <th>총액</th>
      <th>주문일시 </th>
    </tr>
  </thead>
  <tbody>
    {% for order in user.order_set.all %}
    <tr>
      <td>{{ order.shop.name }}</td>
      <td>
        {% for item in order.item_set.all %}
          {{ item.name }}
        {% endfor %}
      </td>
      <td>{{ order.total }}</td>
      <td>{{ order.created_at }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}